print('_'*40)
print('Calculo de aumento salariál')
print('_'*40)
nome = str(input("Digite seu nome: "))
sant = float(input('Digite o seu salário atual: R$ '))
aum = float(input('Digite o valor do aumento: '))
snov = sant +(sant*(aum/100))
print('_'*40)
print('{}, seu novo salário é R${:.2f}'.format(nome, snov))
